Webservice/src/Arcanys/SportizingmeBundle/Entity/User/User.php
<?php

namespace Arcanys\SportizingmeBundle\Entity\User;

use Arcanys\SecurityBundle\Model\UserInterface;
use Arcanys\SecurityBundle\Model\UserSessionInterface;
use Arcanys\SportizingmeBundle\Entity\AbstractTimestamptable;
use Arcanys\SportizingmeBundle\Model\Timestamptable;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * User
 *
 * @ORM\Table(name="users", uniqueConstraints={@ORM\UniqueConstraint(name="unique_idx", columns={"email"})})
 * @ORM\Entity()
 * @ORM\InheritanceType("JOINED")
 * @ORM\DiscriminatorColumn(name="type", type="string")
 * @ORM\DiscriminatorMap({
 *  "athlete" = "Athlete", "sponsor" = "Sponsor", "admin" = "Admin", "gym" = "Gym"
 * })
 * @UniqueEntity(fields={"email"}, groups={"Default","Registration","RegistrationViaFacebook"})
 */
abstract class User extends AbstractTimestamptable implements Timestamptable, UserInterface
{

    const ROLE_DEFAULT = 'ROLE_USER',
            ROLE_ATHLETE = 'ROLE_ATHLETE',
            ROLE_SPONSOR = 'ROLE_SPONSOR',
            ROLE_GYM = 'ROLE_GYM',
            ROLE_ADMIN = 'ROLE_ADMIN',
            ROLE_SUPER_ADMIN = 'ROLE_SUPER_ADMIN';

    /**
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * 
     * @var integer
     */
    protected $id;

    /**
     * @ORM\Column(name="email", type="string", length=128)
     * @Assert\NotBlank(groups={"Default","Registration","RegistrationViaFacebook"})
     * @Assert\Email(groups={"Default","Registration","RegistrationViaFacebook"})
     * 
     * @var string
     */
    protected $email;

    /**
     * @ORM\Column(name="password", type="string", length=255)
     * @Assert\NotBlank(groups={"Registration"})
     * 
     * @var string
     */
    protected $password;

    /**
     * @ORM\Column(name="salt", type="string", length=255)
     * 
     * @var string
     */
    protected $salt;

    /**
     * @ORM\Column(name="roles", type="simple_array")
     * 
     * @var array
     */
    protected $roles;

    /**
     * @ORM\OneToMany(targetEntity="Session", mappedBy="user", cascade={"persist"})
     * @ORM\JoinColumn(name="token_id", referencedColumnName="id", onDelete="SET NULL")
     * 
     * @var \Doctrine\ORM\PersistentCollection
     */
    protected $sessions;

    /**
     * @ORM\Column(name="password_token", type="string", length=255, nullable=true)
     * 
     * @var string
     */
    protected $passwordToken;

    public function __construct($createSession = true)
    {
        if ($createSession) {
            $this->addSession(new Session());
        }
    }
    
    public function addSession(UserSessionInterface $token)
    {
        $token->setUser($this);
        $this->sessions[] = $token;
    }
    
    public function getSessions()
    {
        return $this->sessions;
    }

    public function setSessions($sessions)
    {
        $this->sessions = $sessions;
    }
    
    /**
     * @return Session
     */
    public function getToken()
    {
        if (is_array($this->sessions)) {
            return current($this->sessions);
        }
        return $this->sessions->first();
    }
    
    public function getSession()
    {
        return $this->getToken();
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set email
     *
     * @param string $email
     * @return User
     */
    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Get email
     *
     * @return string 
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set password
     *
     * @param string $password
     * @return User
     */
    public function setPassword($password, $checkSalt = true)
    {
        if ($checkSalt && $this->password !== $password) {
            $this->getSalt(true); // generate new salt
        }
        
        $this->password = $password;

        return $this;
    }

    /**
     * Get password
     *
     * @return string 
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Set salt
     *
     * @param string $salt
     * @return User
     */
    public function setSalt($salt)
    {
        $this->salt = $salt;

        return $this;
    }

    /**
     * Get salt
     *
     * @return string 
     */
    public function getSalt($new = false)
    {
        if (!$this->salt || $new) {
            $this->salt = hash('sha1', rand());
        }
        return $this->salt;
    }

    /**
     * Set roles
     *
     * @param array $roles
     * @return User
     */
    public function setRoles(array $roles)
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * Get roles
     *
     * @return string 
     */
    public function getRoles()
    {
        $this->addRole(static::ROLE_DEFAULT);
        return array_unique($this->roles);
    }
    
    public function addRole($role)
    {
        $this->roles[] = $role;
        
        return $this;
    }

    public function eraseCredentials()
    {
        
    }

    public function getUsername()
    {
        return $this->email;
    }

    public function toArray()
    {
        return array(
            'id' => $this->id,
            'email' => $this->email,
        );
    }
    
    public function getPasswordToken()
    {
        return $this->passwordToken;
    }

    public function setPasswordToken($passwordToken)
    {
        $this->passwordToken = $passwordToken;
    }

}

Webservice/src/Arcanys/SportizingmeBundle/Resources/views/form.html.twig
{# row #}
{% block form_row  %}
{% spaceless %}
                                        {% if not attr.uniform is defined %}
    <div class="form-group {% if errors|length > 0 %}has-error{% endif %}">
        {{ form_label(form) }}
        <div class="{{ block('form_widget_col')|default('col-lg-8') }}">
                                        {% endif %}
            {{ form_widget(form) }}
                                        {% if not attr.uniform is defined %}
        </div>
    </div>
                                        {% endif %}
{% endspaceless %}
{% endblock form_row  %}


{# label #}
{% block form_label %}
{% spaceless %}
    <label class="{{ block('form_label_col')|default('col-lg-3') }} control-label" for="{{ id }}">
        {% if label %}
            {{ label|trans({}, translation_domain) }}
        {% else %}
            {{ name|humanize|trans({}, translation_domain) }}
        {% endif %}
    </label>
{% endspaceless %}
{% endblock form_label %}

{# checkbox #}
{% block checkbox_widget %}
{% spaceless %}
<div class="checkbox">
    <label>
        <input type="checkbox" {{ block('widget_attributes') }}{% if value is defined %} value="{{ value }}"{% endif %}{% if checked %} checked="checked"{% endif %} /> 
        {{ label|trans({}, translation_domain) }}
    </label>
</div>
{% endspaceless %}
{% endblock checkbox_widget %}

{% block choice_widget_expanded %}
{% spaceless %}
    <div {{ block('widget_container_attributes') }}>
    {% for child in form %}
        {{ form_widget(child) }}
        {#{ form_label(child) }#}
    {% endfor %}
    </div>
{% endspaceless %}
{% endblock choice_widget_expanded %}

Webservice/src/Arcanys/SportizingmeBundle/Resources/views/layout.html.twig
{% trans_default_domain "Sportizingme" %}
<!DOCTYPE html>
<html lang="en">
    <head>
    {% block meta %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">
    {% endblock meta %}

    {% block shortcut_icon %}
        <link rel="shortcut icon" href="{{ asset('bundles/arcanyssportizingme/images/adletico-logo.png') }}">
    {% endblock shortcut_icon %}

    {% block title %}
        <title>{{ 'project.title'|trans }}</title>
    {% endblock title %}

    {% block stylesheets %}
        <!-- Bootstrap core CSS -->
        <link href="{{ asset('bundles/arcanyssportizingme/css/bootstrap.min.css') }}" rel="stylesheet">
        <!-- Bootstrap theme -->
        <link href="{{ asset('bundles/arcanyssportizingme/css/bootstrap-theme.min.css') }}" rel="stylesheet">
        <link href="{{ asset('bundles/arcanyssportizingme/css/datepicker.css') }}" rel="stylesheet">

    {% block stylesheets_custom %}
        <!-- Custom styles for this template -->
        <link href="{{ asset('bundles/arcanyssportizingme/css/theme.css') }}" rel="stylesheet">
    {% endblock stylesheets_custom %}
    {% endblock stylesheets %}

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="{{ asset('bundles/arcanyssportizingme/assets/js/html5shiv.js') }}"></script>
          <script src="{{ asset('bundles/arcanyssportizingme/assets/js/respond.min.js') }}"></script>
        <![endif]-->
    </head>

    <body>
    {% block body %}
        {% block navbar %}
        <!-- navbar -->
        <div class="navbar navbar-default navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand brand" href="{{ path('homepage') }}">
                        <img height="28" src="{{ asset('bundles/arcanyssportizingme/images/adletico-logo.png') }}"> 
                        {{ 'project.title'|trans }}
                    </a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                            {% if is_granted('ROLE_SUPER_ADMIN') %}
                            <li><a href="{{ path('sonata_admin_dashboard') }}"><i class="glyphicon glyphicon-dashboard"></i> {{ 'Admin Panel'|trans }}</a></li>
                            {% endif %}
                        {% else %}
                        <li><a href="{{ path('login') }}"><i class="glyphicon glyphicon-log-in"></i> {{ 'Login'|trans }}</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div><!--/ .navbar -->
        {% endblock navbar %}

        {% block container %}
        <div class="container">

            <ul class="breadcrumb">
                <li><a href="{{ path('homepage') }}"><i class="glyphicon glyphicon-home"></i></a></li>
                {% block breadcrumb %}
                {% endblock %}
                <li class="active">
                {% block breadcrumb_active %}
                    {% spaceless %}
                        {{ 'Home'|trans }}
                    {% endspaceless %}
                {% endblock %}
                </li>
            </ul>
            
            {% block errors %}
            {% if app.session.flashbag.has('error') %}
            <div class="alert alert-dismissable alert-danger">
                <button type="button" class="close" data-dismiss="alert">×</button>
                {% for flashMessage in app.session.flashbag.get('error') %}
                <div>{{ flashMessage }}</div>
                {% endfor %}
            </div>
            {% endif %}
            {% endblock errors %}
            
            {% block content %}
            {% endblock content %}
            
        </div> <!-- /container -->
        {% endblock container %}

        {% block javascripts %}
        <!-- Bootstrap core JavaScript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        {% block javascripts_custom %}
        {% endblock javascripts_custom %}
        {% endblock javascripts %}
    {% endblock body %}
    </body>
</html>